version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14  # Most updates should be from the package template
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      rust:  # group all rust deps into a single PR
        patterns:
          - "*"
    cooldown:
      default-days: 7
