repos:
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.23.1
    hooks:
      - id: zizmor
    # This should be before any formatting hooks like isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.4"
    hooks:
      - id: ruff
        args: ["--fix"]
        types: [python]
        # Define here once and then reference using YAML anchor
        exclude: &exclude_dirs ^streamtracer/(data|extern)/
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        types: [python]
        exclude: *exclude_dirs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        types: [python]
        exclude: *exclude_dirs
      - id: check-case-conflict
        types: [python]
        exclude: *exclude_dirs
      - id: trailing-whitespace
        types_or: [python, rst, rust]
      - id: check-yaml
        types: [yaml]
        exclude: *exclude_dirs
      - id: check-toml
        types: [toml]
        exclude: *exclude_dirs
      - id: debug-statements
        types: [python, rust]
        exclude: *exclude_dirs
      - id: check-added-large-files
        args: ["--enforce-all", "--maxkb=1054"]
      - id: end-of-file-fixer
        types_or: [python, rst, rust]
      - id: mixed-line-ending
        types_or: [python, rst, rust]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [ "--write-changes" ]
        types_or: [python, rst, rust]
        exclude: *exclude_dirs
  # Run mypy type validation
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.10.0'
      hooks:
      - id: mypy
        types: [python]
        exclude: *exclude_dirs
        additional_dependencies: [types-setuptools]
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [python]
        exclude: *exclude_dirs
  # Rust code formatting
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.0
    hooks:
      - id: cargo-check
        types: [rust]
      - id: clippy
        args: ["--allow-staged", "--fix", "--", "-A", "clippy::needless_return", "-W", "clippy::implicit_return"]
        types: [rust]
      - id: fmt
        types: [rust]
ci:
  autofix_prs: false
  autoupdate_schedule: "quarterly"
