repos:
    # This should be before any formatting hooks like isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.1"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*|extern.*|streamtracer/extern)$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ".*(.fits|.fts|.fit|.header|.txt)$"
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
        args: ["--enforce-all", "--maxkb=1054"]
      - id: end-of-file-fixer
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*|.json)$|^CITATION.rst$"
      - id: mixed-line-ending
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*)$"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [ "--write-changes" ]
  # Run mypy type validation
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.9.0'
      hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
  # Rust code formatting
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.0
    hooks:
      - id: cargo-check
      - id: clippy
        args: ["--allow-staged", "--fix", "--", "-A", "clippy::needless_return", "-W", "clippy::implicit_return"]
      - id: fmt
ci:
  autofix_prs: false
  autoupdate_schedule: "quarterly"
