repos:
    # This should be before any formatting hooks like isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.1"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ".*(.fits|.fts|.fit|.header|.txt)$"
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
        args: ["--enforce-all", "--maxkb=1054"]
      - id: end-of-file-fixer
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*|.json)$|^CITATION.rst$"
      - id: mixed-line-ending
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*)$"
  # Run mypy type validation
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.8.0'
      hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
        - id: black

ci:
  autofix_prs: false
