
repos:
    # Sort order of Python imports
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
    # Python code formatting
    - repo: https://github.com/psf/black
      rev: 24.2.0
      hooks:
          - id: black
    # Remove unused Python imports
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.2.1
      hooks:
        - id: autoflake
          args: ["--in-place", "--remove-all-unused-imports", "--ignore-init-module-imports"]
    # Run mypy type validation
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v1.8.0'
        hooks:
        - id: mypy
          additional_dependencies: [types-setuptools]


ci:
  autofix_prs: false
